# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuManage', '0002_auto_20170802_1329'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='firstmenus',
            table='meteor_firstmenus',
        ),
        migrations.AlterModelTable(
            name='secondmenus',
            table='meteor_secondmenus',
        ),
    ]
