# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverManage', '0005_auto_20170808_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='expiredate',
            field=models.DateTimeField(blank=True, default=b'2017-08-11 10:09:48', null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4'),
        ),
        migrations.AlterModelTable(
            name='idcs',
            table='meteor_idcs',
        ),
        migrations.AlterModelTable(
            name='projects',
            table='meteor_projects',
        ),
        migrations.AlterModelTable(
            name='servers',
            table='meteor_servers',
        ),
        migrations.AlterModelTable(
            name='services',
            table='meteor_services',
        ),
    ]
