# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverManage', '0009_auto_20170811_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='expiredate',
            field=models.DateTimeField(blank=True, default=b'2017-08-11 10:36:18', null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4'),
        ),
    ]
