# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='iptables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Servers')),
            ],
            options={
                'db_table': 'cmdb_iptables',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffs')),
            ],
            options={
                'db_table': 'cmdb_projects',
            },
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('tags', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Projects')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Servers')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffs')),
            ],
            options={
                'db_table': 'cmdb_services',
            },
        ),
    ]
