# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serverManage', '0002_auto_20170807_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paydns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainname', models.CharField(blank=True, default='', max_length=100)),
                ('ip', models.CharField(blank=True, default='', help_text='\u81ea\u52a8\u751f\u6210', max_length=40)),
                ('comment', models.CharField(blank=True, default='', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverManage.Projects', verbose_name='\u9879\u76ee')),
            ],
            options={
                'ordering': ('project',),
                'db_table': 'classmate_paydns',
            },
        ),
        migrations.CreateModel(
            name='Payhosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, default='', help_text='ip\u6240\u5728\u5730\uff0c\u81ea\u52a8\u751f\u6210', max_length=100)),
                ('comment', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('ip',),
                'db_table': 'classmate_payhosts',
            },
        ),
    ]
