# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thirdManage', '0002_auto_20170807_1622'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paydnses',
            table='classmate_paydnses',
        ),
    ]
