# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdManage', '0003_auto_20170807_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payhosts',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
