# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thirdManage', '0004_auto_20170808_1052'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paydnses',
            table='meteor_paydnses',
        ),
        migrations.AlterModelTable(
            name='payhosts',
            table='meteor_payhosts',
        ),
    ]
