# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userPermission', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dutysheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u4ea4\u63a5\u8bb0\u5f55')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='\u4ea4\u63a5\u65f6\u95f4')),
                ('photo', models.ImageField(default='dutyImg/no-img.png', upload_to='dutyImg', verbose_name='\u4ea4\u63a5\u56fe\u7247')),
                ('deleteTag', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5220\u9664\u6807\u8bb0')),
                ('deleteDate', models.DateTimeField(blank=True, null=True, verbose_name='\u5220\u9664\u65f6\u95f4')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPermission.Staffs', verbose_name='\u4ea4\u63a5\u4eba\u5458')),
            ],
            options={
                'db_table': 'classmate_dutysheets',
                'verbose_name': '\u503c\u73ed\u6587\u6863\u4ea4\u63a5',
            },
        ),
    ]
