# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyManage', '0002_auto_20170713_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutysheets',
            name='photo',
            field=models.ImageField(default='dutyImg/no-img.png', upload_to='dutyImg', verbose_name='\u4ea4\u63a5\u56fe\u7247'),
        ),
    ]
