# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyManage', '0003_auto_20170713_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutysheets',
            name='quantum',
            field=models.CharField(blank=True, choices=[('e', '\u65e9\u73ed'), ('m', '\u4e2d\u73ed'), ('n', '\u665a\u73ed')], default='e', max_length=4, null=True, verbose_name='\u73ed\u6b21'),
        ),
    ]
