# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loganalysis_agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logservice', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u65e5\u5fd7\u6240\u5c5e\u670d\u52a1')),
                ('http_user_agent', models.TextField(blank=True, null=True, verbose_name='\u7528\u6237\u8bbe\u5907\u7c7b\u578b')),
                ('timestamp', models.TextField(blank=True, null=True, verbose_name='\u7edf\u8ba1\u65f6\u95f4')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='\u7edf\u8ba1\u6570')),
            ],
            options={
                'db_table': 'classmate_loganalysis_agent',
                'verbose_name': '\u65e5\u5fd7\u5206\u6790\u7528\u6237\u8bbe\u5907\u7edf\u8ba1',
            },
        ),
        migrations.CreateModel(
            name='Loganalysis_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logservice', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u65e5\u5fd7\u6240\u5c5e\u670d\u52a1')),
                ('clientip', models.TextField(blank=True, null=True, verbose_name='\u7528\u6237\u6240\u5728\u5730\u533a')),
                ('timestamp', models.TextField(blank=True, null=True, verbose_name='\u7edf\u8ba1\u65f6\u95f4')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='\u7edf\u8ba1\u6570')),
            ],
            options={
                'db_table': 'classmate_loganalysis_area',
                'verbose_name': '\u65e5\u5fd7\u5206\u6790\u7528\u6237\u6240\u5728\u5730\u533a\u7edf\u8ba1',
            },
        ),
        migrations.CreateModel(
            name='Loganalysis_cdn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logservice', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u65e5\u5fd7\u6240\u5c5e\u670d\u52a1')),
                ('cdnip', models.TextField(blank=True, null=True, verbose_name='\u7528\u6237\u8bbf\u95ee\u7684cdn\u8282\u70b9ip')),
                ('timestamp', models.TextField(blank=True, null=True, verbose_name='\u7edf\u8ba1\u65f6\u95f4')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='\u7edf\u8ba1\u6570')),
            ],
            options={
                'db_table': 'classmate_loganalysis_cdn',
                'verbose_name': '\u65e5\u5fd7\u5206\u6790\u7528\u6237\u8bbf\u95eecdn\u7edf\u8ba1',
            },
        ),
        migrations.CreateModel(
            name='Loganalysis_http',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logservice', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u65e5\u5fd7\u6240\u5c5e\u670d\u52a1')),
                ('domain', models.TextField(blank=True, null=True, verbose_name='\u7528\u6237\u8bbf\u95ee\u7684\u57df\u540d')),
                ('timestamp', models.TextField(blank=True, null=True, verbose_name='\u7edf\u8ba1\u65f6\u95f4')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='\u7edf\u8ba1\u6570')),
            ],
            options={
                'db_table': 'classmate_loganalysis_http',
                'verbose_name': '\u65e5\u5fd7\u5206\u6790\u7528\u6237\u8bbf\u95ee\u57df\u540d\u7edf\u8ba1',
            },
        ),
        migrations.CreateModel(
            name='Loganalysis_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logservice', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u65e5\u5fd7\u6240\u5c5e\u670d\u52a1')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='\u7528\u6237\u8bbf\u95ee\u72b6\u6001\u7801')),
                ('timestamp', models.TextField(blank=True, null=True, verbose_name='\u7edf\u8ba1\u65f6\u95f4')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='\u7edf\u8ba1\u6570')),
            ],
            options={
                'db_table': 'classmate_loganalysis_status',
                'verbose_name': '\u65e5\u5fd7\u5206\u6790\u7528\u6237\u8bbf\u95ee\u72b6\u6001\u7801\u7edf\u8ba1',
            },
        ),
        migrations.CreateModel(
            name='Loganalysis_upstream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logservice', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u65e5\u5fd7\u6240\u5c5e\u670d\u52a1')),
                ('upstreamaddr', models.TextField(blank=True, null=True, verbose_name='Nginx\u8f6c\u53d1\u5730\u5740')),
                ('timestamp', models.TextField(blank=True, null=True, verbose_name='\u7edf\u8ba1\u65f6\u95f4')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='\u7edf\u8ba1\u6570')),
            ],
            options={
                'db_table': 'classmate_loganalysis_upstream',
                'verbose_name': '\u65e5\u5fd7\u5206\u6790Nginx\u8f6c\u53d1\u7edf\u8ba1',
            },
        ),
    ]
