# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logAnalysis', '0001_initial'),
        ('serverManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loganalysis_upstream',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serverManage.Services', verbose_name='\u670d\u52a1'),
        ),
        migrations.AddField(
            model_name='loganalysis_status',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serverManage.Services', verbose_name='\u670d\u52a1'),
        ),
        migrations.AddField(
            model_name='loganalysis_http',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serverManage.Services', verbose_name='\u670d\u52a1'),
        ),
        migrations.AddField(
            model_name='loganalysis_cdn',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serverManage.Services', verbose_name='\u670d\u52a1'),
        ),
        migrations.AddField(
            model_name='loganalysis_area',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serverManage.Services', verbose_name='\u670d\u52a1'),
        ),
        migrations.AddField(
            model_name='loganalysis_agent',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serverManage.Services', verbose_name='\u670d\u52a1'),
        ),
    ]
