# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logAnalysis', '0002_auto_20170802_1329'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loganalysis_agent',
            table='meteor_loganalysis_agent',
        ),
        migrations.AlterModelTable(
            name='loganalysis_area',
            table='meteor_loganalysis_area',
        ),
        migrations.AlterModelTable(
            name='loganalysis_cdn',
            table='meteor_loganalysis_cdn',
        ),
        migrations.AlterModelTable(
            name='loganalysis_http',
            table='meteor_loganalysis_http',
        ),
        migrations.AlterModelTable(
            name='loganalysis_status',
            table='meteor_loganalysis_status',
        ),
        migrations.AlterModelTable(
            name='loganalysis_upstream',
            table='meteor_loganalysis_upstream',
        ),
    ]
