# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menuManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'db_table': 'meteor_groups',
            },
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(default='1000', max_length=4)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'db_table': 'meteor_rolepermissions',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'db_table': 'meteor_roles',
            },
        ),
        migrations.CreateModel(
            name='StaffPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(default='1000', max_length=4)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
                ('secondmenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuManage.Secondmenus', verbose_name='\u5b50\u83dc\u5355')),
            ],
            options={
                'db_table': 'meteor_staffpermissions',
            },
        ),
        migrations.CreateModel(
            name='StaffRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPermission.Roles', verbose_name='\u89d2\u8272')),
            ],
            options={
                'db_table': 'meteor_staffroles',
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('sex', models.CharField(blank=True, max_length=2, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('telno', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPermission.Groups')),
            ],
            options={
                'db_table': 'meteor_staffs',
            },
        ),
        migrations.AddField(
            model_name='staffroles',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPermission.Staffs', verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='staffpermissions',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPermission.Staffs', verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPermission.Roles', verbose_name='\u89d2\u8272'),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='secondmenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuManage.Secondmenus', verbose_name='\u5b50\u83dc\u5355'),
        ),
    ]
