# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'db_table': 'meteor_groups',
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('sex', models.CharField(blank=True, max_length=2, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('telno', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPermission.Groups')),
            ],
            options={
                'db_table': 'meteor_staffs',
            },
        ),
    ]
