# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'db_table': 'cmdb_idcs',
            },
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('cpu', models.CharField(max_length=15)),
                ('memory', models.CharField(max_length=15)),
                ('disktype', models.CharField(max_length=15)),
                ('disksize', models.CharField(max_length=15)),
                ('netcard', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=100)),
                ('servermodel', models.CharField(max_length=50)),
                ('validdate', models.CharField(max_length=15)),
                ('uuid', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Idcs')),
            ],
            options={
                'db_table': 'cmdb_servers',
            },
        ),
    ]
