# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20170606_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='comment',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='servers',
            name='cpu',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='servers',
            name='disksize',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='servers',
            name='disktype',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='servers',
            name='idc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Idcs'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='memory',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='servers',
            name='netcard',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servers',
            name='provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='servers',
            name='servermodel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servers',
            name='uuid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servers',
            name='validdate',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
