# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menuManage', '0001_initial'),
        ('userPermission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operaterecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userip', models.CharField(blank=True, max_length=15)),
                ('date', models.DateTimeField(default=b'2017-08-17 13:18:47', verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('operate', models.CharField(choices=[('add', '\u6dfb\u52a0'), ('delete', '\u5220\u9664'), ('modify', '\u4fee\u6539'), ('view', '\u67e5\u770b'), ('login', '\u767b\u5165')], max_length=6)),
                ('olddata', models.TextField(blank=True)),
                ('newdata', models.TextField(blank=True)),
                ('comment', models.CharField(blank=True, max_length=160, null=True)),
                ('secondmenu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menuManage.Secondmenus', verbose_name='\u64cd\u4f5c\u6a21\u5757')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userPermission.Staffs', verbose_name='\u64cd\u4f5c\u7528\u6237')),
            ],
            options={
                'db_table': 'meteor_operaterecords',
            },
        ),
    ]
