# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operateRecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaterecords',
            name='date',
            field=models.DateTimeField(default=b'2017-08-11 11:57:50', verbose_name='\u64cd\u4f5c\u65f6\u95f4'),
        ),
    ]
