# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operateRecord', '0006_auto_20170811_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaterecords',
            name='date',
            field=models.DateTimeField(default=b'2017-08-11 17:03:19', verbose_name='\u64cd\u4f5c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='operaterecords',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userPermission.Staffs', verbose_name='\u64cd\u4f5c\u7528\u6237'),
        ),
    ]
