# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operateRecord', '0007_auto_20170811_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='operaterecords',
            name='comment',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='operaterecords',
            name='date',
            field=models.DateTimeField(default=b'2017-08-14 10:36:17', verbose_name='\u64cd\u4f5c\u65f6\u95f4'),
        ),
    ]
