# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operateRecord', '0008_auto_20170814_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaterecords',
            name='date',
            field=models.DateTimeField(default=b'2017-08-14 11:05:51', verbose_name='\u64cd\u4f5c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='operaterecords',
            name='secondmenu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menuManage.Secondmenus', verbose_name='\u64cd\u4f5c\u6a21\u5757'),
        ),
    ]
